spring:
  cloud:
    stream:
      function:
        definition : paymentProcessor
      bindings:
        paymentProcessor-in-0 : # Komsumen
          destination: order-event
        paymentProcessor-out-0 : # Produsen
          destination: payment-event



server:
  port: 8082